### ISSUE TITLE
Creating remote container before a local one breaks flow

### ISSUE THREAD

**Issue by shimil** [wix/remote-dom#19]
All following messages, relying on the containers to be synced, also fail.

**Comment by avi** [comment]
Don't try to control ordering, local side needs to buffer messages until it is ready... not entirely sure this should be solved inside the library, it seems like a problem that can/should be handled externally...

**Comment by shimil** [comment]
@avi I did add a buffer for messages locally. Didn't try to control the ordering. It's a problem doing it externally, since there might be messages arriving for different containers on the same channel, and we don't know which container it belongs to (until it is attached to it). Also, we don't have an outside indication of whether the messages were processed successfully or not.
